version: "3"
services:
  api:
    image: kun391/phpup:1.1
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - db
    volumes:
      - ./src:/var/www/app
      - ./deployment/certs/cert.pem:/etc/nginx/www-ssl/certificate.crt
      - ./deployment/certs/private.key:/etc/nginx/www-ssl/privateKey.key
      - ./deployment/configs/queue.conf:/etc/supervisor/conf.d/queue.conf
      - ./deployment/configs/nginx.conf:/etc/nginx/sites-enabled/default.conf
      - ./deployment/configs/nginx.ssl.conf:/etc/nginx/sites-enabled/default.ssl.conf
    environment:
      - PHP_MEM_LIMIT=${PHP_MEM_LIMIT}
  # container for database
  s3:
    image: bitnami/minio:latest
    ports:
      - ${MINIO_PORT}:9000
    volumes:
      - ${PATH_TO_STORAGE}:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # container for UI database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPADMIN_PORT}:80
    depends_on:
      - db
    environment:
      PMA_HOSTS: ${MYSQL_DATABASE}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
